from __future__ import annotations

from typing import List

# Curated from manually inspected RLVR rollouts (architecture v0.2 sketch).
# Sorted by decreasing expected precision.
REVERSAL_MARKERS: List[str] = [
    "wait",
    "actually",
    "let me reconsider",
    "that's not right",
    "i made an error",
    "let me try again",
    "hold on",
    "no wait",
    "i think i was wrong",
    "let me restart",
    "going back",
    "actually no",
    "that approach won't work",
    "i need to rethink",
    "this is wrong",
    "i got confused",
    "let me recalculate",
    "scratch that",
    "on second thought",
    "i realize i've been",
    "my previous reasoning was",
    "i made a mistake",
    "correction:",
    "i need to revise",
    "let me redo",
    "that doesn't work because",
    "i was wrong about",
    "re-examining",
    "looking at this again",
    "i think i overcomplicated",
    "stepping back",
    "to reconsider",
    "i realize now",
    "i missed",
    "let me be more careful",
    "i'm going in the wrong direction",
    "different approach",
    "i should",
    "more carefully",
    "rechecking",
    "alternative:",
    "approach 2",
    "method 2",
    "try differently",
    "from the start",
    # VLM extensions:
    "let me look at the image again",
    "i may have misread",
    "looking more carefully",
    "i think i misidentified",
    "the image actually shows",
    "on second look",
]
